(setq projectile-completion-system 'grizzl)
(setq exec-path (append exec-path '("/usr/local/bin/")))
(global-set-key (kbd "<home>") 'move-beginning-of-line)
(global-set-key (kbd "<end>") 'move-end-of-line)
(setq-default indent-tabs-mode nil)
